### ISSUE TITLE
Atualizar Preço dos Produtos em lote.

### ISSUE THREAD

**Issue by gabriel-aoliveira** [Fabiorohem/Talos#54]
**A funcionalidade que você está solicitando tem a ver com algum problema? Descreva.**
Não existe problema, o desconfortável é que quando uma marca "Piraquê" altera o preço de um produto deles para o cliente, o mesmo precisa entrar em cada item para ajustar.

**Descreva a solução que você gostaria que tivesse**
No campo "buscar", ao digitar o produto desejado, ter a opção de selecionar os produtos que queremos alterar o preço em lote, normalmente tem um aumento em um determinado produto de 20% e etc.

Essa Ideia foi do Gerente da DRI COMÉRCIO, pois isso acontece com frequência na loja.

**Comment by Fabiorohem** [comment]
A melhoria foi implantada no commit acima
